"use client";

import { useEffect, useRef, useState } from "react";

export default function NormalizedProductImage({src,alt,normalize}:{src:string;alt:string;normalize:boolean}){
 const canvasRef=useRef<HTMLCanvasElement>(null);const[ready,setReady]=useState(false);const[failed,setFailed]=useState(false);
 useEffect(()=>{if(!normalize){setFailed(true);return}let cancelled=false;const image=new Image();image.crossOrigin="anonymous";image.onload=()=>{if(cancelled)return;try{const sample=document.createElement("canvas"),size=320,scale=Math.min(1,size/Math.max(image.naturalWidth,image.naturalHeight));sample.width=Math.max(1,Math.round(image.naturalWidth*scale));sample.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=sample.getContext("2d",{willReadFrequently:true});if(!context)throw new Error();context.drawImage(image,0,0,sample.width,sample.height);const pixels=context.getImageData(0,0,sample.width,sample.height).data;const corners=[[0,0],[sample.width-1,0],[0,sample.height-1],[sample.width-1,sample.height-1]];const background=corners.reduce((value,[x,y])=>{const index=(y*sample.width+x)*4;value[0]+=pixels[index];value[1]+=pixels[index+1];value[2]+=pixels[index+2];value[3]+=pixels[index+3];return value},[0,0,0,0]).map(value=>value/4);let minX=sample.width,minY=sample.height,maxX=-1,maxY=-1;for(let y=0;y<sample.height;y++)for(let x=0;x<sample.width;x++){const index=(y*sample.width+x)*4,alpha=pixels[index+3],distance=Math.hypot(pixels[index]-background[0],pixels[index+1]-background[1],pixels[index+2]-background[2]);if(alpha>35&&(background[3]<80||distance>38)){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}}if(maxX<minX||maxY<minY)throw new Error();const sourceX=minX/scale,sourceY=minY/scale,sourceWidth=(maxX-minX+1)/scale,sourceHeight=(maxY-minY+1)/scale;const canvas=canvasRef.current;if(!canvas)return;canvas.width=900;canvas.height=900;const output=canvas.getContext("2d");if(!output)throw new Error();output.clearRect(0,0,900,900);const targetHeight=720,targetWidth=Math.min(700,sourceWidth/sourceHeight*targetHeight),drawHeight=Math.min(targetHeight,targetWidth*sourceHeight/sourceWidth),drawWidth=drawHeight*sourceWidth/sourceHeight;output.drawImage(image,sourceX,sourceY,sourceWidth,sourceHeight,(900-drawWidth)/2,(900-drawHeight)/2,drawWidth,drawHeight);setReady(true)}catch{setFailed(true)}};image.onerror=()=>setFailed(true);image.src=src;return()=>{cancelled=true}},[src,normalize]);
 if(failed)return <img src={src} alt={alt}/>;
 return <canvas ref={canvasRef} className={ready?"normalizedProductImage ready":"normalizedProductImage"} role="img" aria-label={alt}/>;
}
