import "server-only";

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", "\"": "&quot;" })[character] || character);

type ProposedOrder={items:Array<{name:string;quantity:number;unitPrice:number;ice:string;sugar:string;note:string;toppings:Array<{name:string;price:number}>;comboItems:Array<{name:string;ice:string;sugar:string;note:string;toppings:Array<{name:string;price:number}>}>}>;subtotal:number;tax:number;total:number};
const dollars=(value:number)=>`$${Number(value||0).toFixed(2)}`;
const itemDetails=(item:ProposedOrder["items"][number])=>[item.ice&&`Ice: ${item.ice}`,item.sugar&&`Sugar: ${item.sugar}`,item.toppings.length&&`Toppings: ${item.toppings.map(t=>t.name).join(", ")}`,item.note&&`Note: ${item.note}`].filter(Boolean).join(" · ");
const proposedMenuHtml=(order:ProposedOrder)=>order.items.length?`<h2 style="font-family:Georgia,serif;margin-top:28px">Proposed event menu</h2><div>${order.items.map(item=>`<div style="padding:12px 0;border-bottom:1px solid #dce5df"><b>${item.quantity} × ${escapeHtml(item.name)}</b><span style="float:right">${escapeHtml(dollars(item.unitPrice*item.quantity))}</span>${itemDetails(item)?`<div style="color:#60736a;font-size:13px;margin-top:5px">${escapeHtml(itemDetails(item))}</div>`:""}${item.comboItems.map(child=>`<div style="margin:7px 0 0 16px;font-size:13px"><b>${escapeHtml(child.name)}</b>${itemDetails({...child,quantity:1,unitPrice:0,comboItems:[]})?` · ${escapeHtml(itemDetails({...child,quantity:1,unitPrice:0,comboItems:[]}))}`:""}</div>`).join("")}</div>`).join("")}</div><p><b>Subtotal:</b> ${dollars(order.subtotal)}<br><b>Tax estimate:</b> ${dollars(order.tax)}<br><b>Estimated total:</b> ${dollars(order.total)}</p><p style="color:#80601e"><b>Estimate only.</b> No order or payment has been created.</p>`:`<p><b>Proposed menu:</b> No menu items selected.</p>`;

export async function sendEventBookingEmail(input: { id: string; referenceCode: string; eventName: string; eventDate: string; startTime: string; customerName: string; customerPhone: string; customerEmail: string; guestCount: number | null; notes: string; proposedOrder: ProposedOrder; to: string }) {
  const apiKey = process.env.RESEND_API_KEY?.trim();
  const from = process.env.EVENT_BOOKING_FROM_EMAIL?.trim() || process.env.GIFT_CARD_FROM_EMAIL?.trim();
  if (!apiKey || !from || !input.to) return { status: "not_configured" as const };
  const response = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json", "Idempotency-Key": `event-booking/${input.id}` }, body: JSON.stringify({ from, to: [input.to], subject: `New event request · ${input.eventName} · ${input.referenceCode}`, html: `<div style="font-family:Arial,sans-serif;color:#153b2e;max-width:620px"><p style="font-weight:800;letter-spacing:.12em">LEVIEN CAFE</p><h1 style="font-family:Georgia,serif">New event booking request</h1><p><b>Reference:</b> ${escapeHtml(input.referenceCode)}</p><p><b>Event:</b> ${escapeHtml(input.eventName)}</p><p><b>Date and time:</b> ${escapeHtml(input.eventDate)} at ${escapeHtml(input.startTime)}</p><p><b>Customer:</b> ${escapeHtml(input.customerName || "Not provided")}</p><p><b>Phone:</b> ${escapeHtml(input.customerPhone || "Not provided")}</p><p><b>Email:</b> ${escapeHtml(input.customerEmail || "Not provided")}</p><p><b>Guests:</b> ${input.guestCount ?? "Not provided"}</p><p><b>Details:</b><br>${escapeHtml(input.notes || "No additional details")}</p>${proposedMenuHtml(input.proposedOrder)}<p>Open Admin → Event Bookings to review and update this request.</p></div>` }) });
  if (!response.ok) throw new Error("Unable to send event booking email.");
  return { status: "sent" as const };
}
