"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

type MenuItem={name:string;quantity:number;unitPrice:number;ice?:string;sugar?:string;note?:string;toppings?:Array<{name:string;price:number}>;comboItems?:Array<{name:string;ice?:string;sugar?:string;note?:string;toppings?:Array<{name:string;price:number}>}>};
type ProposedOrder={items:MenuItem[];subtotal:number;tax:number;total:number};
type Booking={id:string;reference_code:string;event_name:string;event_type:string;event_date:string;start_time:string;end_time:string|null;customer_name:string;customer_phone:string;customer_email:string|null;guest_count:number|null;notes:string;admin_note:string;status:"new"|"contacted"|"confirmed"|"cancelled";created_at:string;proposed_order?:ProposedOrder};
const labels={new:"New",contacted:"Contacted",confirmed:"Confirmed",cancelled:"Cancelled"};
const money=(value:number)=>`$${Number(value||0).toFixed(2)}`;
const options=(item:{ice?:string;sugar?:string;note?:string;toppings?:Array<{name:string}>})=>[item.ice&&`Ice ${item.ice}`,item.sugar&&`Sugar ${item.sugar}`,...(item.toppings||[]).map(t=>`+ ${t.name}`),item.note&&`Note: ${item.note}`].filter(Boolean).join(" · ");
export default function EventBookings({notify,focusId}:{notify:(message:string)=>void;focusId?:string}){
 const [items,setItems]=useState<Booking[]>([]),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(true),[saving,setSaving]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/admin/event-bookings",{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error);setItems(x.requests||[])}catch(e){notify(e instanceof Error?e.message:"Unable to load event bookings")}finally{setLoading(false)}},[notify]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{if(focusId)requestAnimationFrame(()=>document.getElementById(`event-${focusId}`)?.scrollIntoView({behavior:"smooth",block:"center"}))},[focusId,items]);
 const shown=useMemo(()=>items.filter(item=>filter==="all"||item.status===filter),[items,filter]);
 async function save(item:Booking){setSaving(item.id);try{const r=await fetch("/api/admin/event-bookings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(item)});const x=await r.json();if(!r.ok)throw new Error(x.error);setItems(current=>current.map(entry=>entry.id===item.id?x.request:entry));notify("Event booking updated")}catch(e){notify(e instanceof Error?e.message:"Unable to update booking")}finally{setSaving("")}}
 const edit=(id:string,patch:Partial<Booking>)=>setItems(current=>current.map(item=>item.id===id?{...item,...patch}:item));
 return <div className="eventAdminStack"><section className="adminToolbar"><div className="adminTabs">{["all","new","contacted","confirmed","cancelled"].map(status=><button type="button" className={filter===status?"active":""} onClick={()=>setFilter(status)} key={status}>{status==="all"?"All":labels[status as keyof typeof labels]}<span>{items.filter(item=>status==="all"||item.status===status).length}</span></button>)}</div><button className="adminSecondary" type="button" onClick={()=>void refresh()}>{loading?"Loading…":"Refresh"}</button></section>
 <section className="eventAdminGrid">{shown.map(item=><article className={`adminCard eventBookingAdminCard ${focusId===item.id?"focused":""}`} id={`event-${item.id}`} key={item.id}><header><div><span className="adminEyebrow">{item.reference_code}</span><h3>{item.event_name}</h3><p>{item.event_date} · {item.start_time.slice(0,5)}{item.end_time?`–${item.end_time.slice(0,5)}`:""} · {item.guest_count||"—"} guests</p></div><select value={item.status} onChange={e=>edit(item.id,{status:e.target.value as Booking["status"]})}>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></header><div className="eventBookingContact"><strong>{item.customer_name||"Name not provided"}</strong><a href={`tel:${item.customer_phone}`}>{item.customer_phone||"Phone not provided"}</a>{item.customer_email&&<a href={`mailto:${item.customer_email}`}>{item.customer_email}</a>}</div>{item.proposed_order?.items?.length?<section className="eventBookingMenu wide"><header><div><strong>Proposed menu</strong><span>{item.proposed_order.items.reduce((sum,menuItem)=>sum+menuItem.quantity,0)} item(s)</span></div><b>{money(item.proposed_order.total)} estimated</b></header>{item.proposed_order.items.map((menuItem,index)=><div className="eventBookingMenuItem" key={`${menuItem.name}-${index}`}><div><strong>{menuItem.quantity} × {menuItem.name}</strong>{options(menuItem)&&<small>{options(menuItem)}</small>}{menuItem.comboItems?.map((child,childIndex)=><span key={`${child.name}-${childIndex}`}><b>{child.name}</b>{options(child)&&<small>{options(child)}</small>}</span>)}</div><b>{money(menuItem.unitPrice*menuItem.quantity)}</b></div>)}<footer><span>Subtotal {money(item.proposed_order.subtotal)} · Tax {money(item.proposed_order.tax)}</span><small>Estimate only — not a confirmed order or payment.</small></footer></section>:<div className="eventBookingMenuEmpty wide">No menu items requested.</div>}<label>Event date<input type="date" value={item.event_date} onChange={e=>edit(item.id,{event_date:e.target.value})}/></label><label>Start time<input type="time" value={item.start_time.slice(0,5)} onChange={e=>edit(item.id,{start_time:e.target.value})}/></label><label className="wide">Customer details<textarea rows={3} value={item.notes} onChange={e=>edit(item.id,{notes:e.target.value})}/></label><label className="wide">Private admin note<textarea rows={3} value={item.admin_note} onChange={e=>edit(item.id,{admin_note:e.target.value})}/></label><button className="adminPrimary wide" type="button" disabled={saving===item.id} onClick={()=>void save(item)}>{saving===item.id?"Saving…":"Save booking"}</button></article>)}{!shown.length&&!loading&&<div className="adminCard workforceEmpty"><strong>No event bookings</strong><span>New requests will appear here automatically.</span></div>}</section></div>;
}
