"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type PromotionType = "percent_off" | "fixed_off" | "buy_x_get_y";
type ScopeType = "all" | "products" | "categories" | "combos";
type Promotion = { id:string; name:string; badge_text:string; description:string; promotion_type:PromotionType; scope_type:ScopeType; target_ids:string[]; discount_value:number; buy_quantity:number; get_quantity:number; reward_product_id:string|null; reward_product_ids:string[]; reward_topping_id:string|null; minimum_subtotal:number; usage_limit:number|null; usage_count:number; starts_on:string; ends_on:string; active:boolean };
type Choice = { id:string; name:string; price?:number };
type Catalog = { products:Choice[]; categories:Choice[]; combos:Choice[]; toppings:Choice[] };
const today = () => new Date().toISOString().slice(0,10);
const formatDate = (value:string) => new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(`${value}T00:00:00`));

function ChoicePicker({title,hint,name,items,selected,onChange}:{title:string;hint:string;name:string;items:Choice[];selected:string[];onChange:(ids:string[])=>void}) {
  const [query,setQuery]=useState("");
  const visible=items.filter(item=>item.name.toLowerCase().includes(query.trim().toLowerCase()));
  const toggle=(id:string)=>onChange(selected.includes(id)?selected.filter(value=>value!==id):[...selected,id]);
  return <fieldset className="loyaltyProductPicker wide"><legend>{title} <span>{hint}</span></legend><div className="promotionPickerTools"><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search…"/><button type="button" className="adminTextButton" onClick={()=>onChange(items.map(item=>item.id))}>Select all</button><button type="button" className="adminTextButton muted" onClick={()=>onChange([])}>Clear</button><strong>{selected.length} selected</strong></div><div className="loyaltyProductGrid">{visible.map(item=><label key={item.id} className="loyaltyProductChoice"><input name={name} type="checkbox" value={item.id} checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/><span><strong>{item.name}</strong>{typeof item.price==="number"&&<small>${item.price.toFixed(2)}</small>}</span></label>)}</div></fieldset>;
}

export default function SalesPromotions({catalog,notify}:{catalog:Catalog;notify:(message:string)=>void}) {
  const [items,setItems]=useState<Promotion[]>([]),[editing,setEditing]=useState<Promotion|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showForm,setShowForm]=useState(false);
  const [type,setType]=useState<PromotionType>("percent_off"),[scope,setScope]=useState<ScopeType>("products"),[targets,setTargets]=useState<string[]>([]),[rewards,setRewards]=useState<string[]>([]),[error,setError]=useState("");
  const refresh=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/admin/sales-promotions",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error);setItems(result.promotions||[])}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load promotions")}finally{setLoading(false)}},[]);
  useEffect(()=>{void refresh()},[refresh]);
  const targetChoices=useMemo(()=>scope==="categories"?catalog.categories:scope==="combos"?catalog.combos:catalog.products,[scope,catalog]);
  function openCreate(){setEditing(null);setType("percent_off");setScope("products");setTargets([]);setRewards([]);setError("");setShowForm(true)}
  function openEdit(item:Promotion){setEditing(item);setType(item.promotion_type);setScope(item.scope_type);setTargets(item.target_ids||[]);setRewards(item.reward_product_ids?.length?item.reward_product_ids:item.reward_product_id?[item.reward_product_id]:[]);setError("");setShowForm(true)}
  function close(){if(saving)return;setShowForm(false);setEditing(null);setError("")}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(saving)return;const form=new FormData(event.currentTarget);if(scope!=="all"&&!targets.length)return setError("Choose at least one eligible item.");if(type==="buy_x_get_y"&&!rewards.length&&!form.get("rewardToppingId"))return setError("Choose at least one reward product or a free topping.");setSaving(true);setError("");try{const response=await fetch("/api/admin/sales-promotions",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:editing?.id,name:form.get("name"),badgeText:form.get("badgeText"),description:form.get("description"),promotionType:type,scopeType:scope,targetIds:scope==="all"?[]:targets,discountValue:Number(form.get("discountValue")),buyQuantity:Number(form.get("buyQuantity")),getQuantity:Number(form.get("getQuantity")),rewardProductIds:rewards,rewardToppingId:form.get("rewardToppingId"),minimumSubtotal:Number(form.get("minimumSubtotal")),usageLimit:form.get("usageLimit")?Number(form.get("usageLimit")):null,startsOn:form.get("startsOn"),endsOn:form.get("endsOn"),active:form.get("active")==="on"})});const result=await response.json();if(!response.ok)throw new Error(result.error);notify(editing?"Promotion updated":"Promotion created");close();await refresh()}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save promotion")}finally{setSaving(false)}}
  async function toggle(item:Promotion){const response=await fetch("/api/admin/sales-promotions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,name:item.name,badgeText:item.badge_text,description:item.description,promotionType:item.promotion_type,scopeType:item.scope_type,targetIds:item.target_ids,discountValue:item.discount_value,buyQuantity:item.buy_quantity,getQuantity:item.get_quantity,rewardProductIds:item.reward_product_ids||[],rewardToppingId:item.reward_topping_id,minimumSubtotal:item.minimum_subtotal,usageLimit:item.usage_limit,startsOn:item.starts_on,endsOn:item.ends_on,active:!item.active})});if(!response.ok){const result=await response.json();return setError(result.error||"Unable to update promotion")};notify(item.active?"Promotion paused":"Promotion activated");await refresh()}

  return <div className="adminStack salesPromotionAdmin">{error&&!showForm&&<div className="adminLoginError" role="alert">{error}</div>}<section className="adminCard"><div className="adminCardHead"><div><span className="adminEyebrow">Pricing and rewards</span><h3>Promotions</h3></div><button className="adminPrimary" type="button" onClick={openCreate}>Create Promotion</button></div><div className="loyaltyRuleRows">{loading?<p>Loading promotions…</p>:items.length?items.map(item=><article key={item.id}><div><strong>{item.name}</strong><span>{item.badge_text} · {item.promotion_type==="buy_x_get_y"?`Buy ${item.buy_quantity}, get ${item.get_quantity}`:item.promotion_type==="percent_off"?`${item.discount_value}% off`:`$${item.discount_value.toFixed(2)} off`}</span><small>{formatDate(item.starts_on)} – {formatDate(item.ends_on)} · {item.usage_count}{item.usage_limit?`/${item.usage_limit}`:""} uses</small></div><div className="adminRowActions"><button className="adminTextButton" onClick={()=>openEdit(item)}>Edit</button><button className={item.active?"adminSecondary":"adminPrimary"} onClick={()=>void toggle(item)}>{item.active?"Pause":"Activate"}</button></div></article>):<p>No promotions yet.</p>}</div></section>
  {showForm&&<div className="adminModalBackdrop" onMouseDown={event=>{if(event.currentTarget===event.target)close()}}><div className="adminModal loyaltyProgramModal" role="dialog" aria-modal="true" aria-labelledby="sales-promotion-title"><header><div><span className="adminEyebrow">Pricing and rewards</span><h2 id="sales-promotion-title">{editing?"Edit promotion":"Create promotion"}</h2></div><button type="button" onClick={close} disabled={saving} aria-label="Close">×</button></header>{error&&<div className="adminLoginError" role="alert">{error}</div>}<form className="adminForm" onSubmit={save}>
    <label>Promotion name<input name="name" defaultValue={editing?.name||""} required/></label><label>Customer badge<input name="badgeText" defaultValue={editing?.badge_text||"Special offer"} required/></label><label>Promotion type<select value={type} onChange={event=>setType(event.target.value as PromotionType)}><option value="percent_off">Percentage discount</option><option value="fixed_off">Fixed amount discount</option><option value="buy_x_get_y">Buy X, get Y</option></select></label><label>Applies to<select value={scope} onChange={event=>{setScope(event.target.value as ScopeType);setTargets([])}}><option value="all">Entire order</option><option value="products">Selected products</option><option value="categories">Selected categories</option><option value="combos">Selected combos</option></select></label>
    {type!=="buy_x_get_y"&&<label>{type==="percent_off"?"Discount percentage":"Discount amount"}<input name="discountValue" type="number" min="0.01" max={type==="percent_off"?100:undefined} step="0.01" defaultValue={editing?.discount_value||""} required/></label>}<label>Minimum subtotal<input name="minimumSubtotal" type="number" min="0" step="0.01" defaultValue={editing?.minimum_subtotal||0}/></label>
    {type==="buy_x_get_y"&&<><label>Buy quantity<input name="buyQuantity" type="number" min="1" defaultValue={editing?.buy_quantity||1} required/></label><label>Free quantity<input name="getQuantity" type="number" min="1" defaultValue={editing?.get_quantity||1} required/></label></>}
    {scope!=="all"&&<ChoicePicker title={type==="buy_x_get_y"?"Products customers must buy":"Products receiving the promotion"} hint="Choose one or more eligible items." name="targetIds" items={targetChoices} selected={targets} onChange={setTargets}/>}
    {type==="buy_x_get_y"&&<ChoicePicker title="Reward product choices" hint="Customers may choose from any selected reward product." name="rewardProductIds" items={catalog.products} selected={rewards} onChange={setRewards}/>}
    {type==="buy_x_get_y"&&<label>Or free topping<select name="rewardToppingId" defaultValue={editing?.reward_topping_id||""}><option value="">No free topping</option>{catalog.toppings.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
    <label>Usage limit <small>Optional</small><input name="usageLimit" type="number" min="1" defaultValue={editing?.usage_limit||""}/></label><label>Start date<input name="startsOn" type="date" defaultValue={editing?.starts_on||today()} required/></label><label>End date<input name="endsOn" type="date" min={editing?.starts_on||today()} defaultValue={editing?.ends_on||today()} required/></label><label className="wide">Description<textarea name="description" rows={3} defaultValue={editing?.description||""}/></label><label className="adminCheck wide"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/> Active within selected date range</label><div className="adminFormActions wide"><button className="adminSecondary" type="button" onClick={close} disabled={saving}>Cancel</button><button className="adminPrimary" disabled={saving}>{saving?"Saving…":editing?"Save Promotion":"Create Promotion"}</button></div>
  </form></div></div>}</div>;
}
