"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Promotion={id:string;name:string;badge_text:string;description:string;promotion_type:"percent_off"|"fixed_off"|"buy_x_get_y";scope_type:"all"|"products"|"categories"|"combos";target_ids:string[];discount_value:number;buy_quantity:number;get_quantity:number;reward_product_id:string|null;reward_topping_id:string|null;minimum_subtotal:number;usage_limit:number|null;usage_count:number;starts_on:string;ends_on:string;active:boolean};
type Catalog={products:Array<{id:string;name:string}>;categories:Array<{id:string;name:string}>;combos:Array<{id:string;name:string}>;toppings:Array<{id:string;name:string}>};
const today=()=>new Date().toISOString().slice(0,10);
export default function SalesPromotions({catalog,notify}:{catalog:Catalog;notify:(message:string)=>void}){
 const [items,setItems]=useState<Promotion[]>([]),[editing,setEditing]=useState<Promotion|null>(null),[loading,setLoading]=useState(true),[scope,setScope]=useState<Promotion["scope_type"]>("all");
 const refresh=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/admin/sales-promotions",{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error);setItems(x.promotions||[])}catch(e){notify(e instanceof Error?e.message:"Unable to load promotions")}finally{setLoading(false)}},[notify]);
 useEffect(()=>{void refresh()},[refresh]);
 function beginEdit(item:Promotion){setEditing(item);setScope(item.scope_type)}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const body={id:editing?.id,name:f.get("name"),badgeText:f.get("badgeText"),description:f.get("description"),promotionType:f.get("promotionType"),scopeType:scope,targetIds:scope==="all"?[]:f.getAll("targetIds"),discountValue:Number(f.get("discountValue")),buyQuantity:Number(f.get("buyQuantity")),getQuantity:Number(f.get("getQuantity")),rewardProductId:f.get("rewardProductId"),rewardToppingId:f.get("rewardToppingId"),minimumSubtotal:Number(f.get("minimumSubtotal")),usageLimit:f.get("usageLimit")?Number(f.get("usageLimit")):null,startsOn:f.get("startsOn"),endsOn:f.get("endsOn"),active:f.get("active")==="on"};try{const r=await fetch("/api/admin/sales-promotions",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.error);notify(editing?"Promotion updated":"Promotion created");setEditing(null);setScope("all");event.currentTarget.reset();await refresh()}catch(e){notify(e instanceof Error?e.message:"Unable to save promotion")}}
 const edit=editing,targets=scope==="categories"?catalog.categories:scope==="combos"?catalog.combos:catalog.products;
 return <div className="adminStack"><section className="adminCard"><div className="adminCardHead"><div><span className="adminEyebrow">Pricing and rewards</span><h3>{edit?"Edit promotion":"New promotion"}</h3></div>{edit&&<button className="adminSecondary" onClick={()=>{setEditing(null);setScope("all")}}>Cancel edit</button>}</div><form className="adminForm" onSubmit={save} key={edit?.id||"new"}>
  <label>Promotion name<input name="name" defaultValue={edit?.name||""} required/></label><label>Customer badge<input name="badgeText" defaultValue={edit?.badge_text||"Special offer"} required/></label>
  <label>Promotion type<select name="promotionType" defaultValue={edit?.promotion_type||"percent_off"}><option value="percent_off">Percentage discount</option><option value="fixed_off">Fixed amount discount</option><option value="buy_x_get_y">Buy X, get Y</option></select></label><label>Applies to<select name="scopeType" value={scope} onChange={e=>setScope(e.target.value as Promotion["scope_type"])}><option value="all">Entire order</option><option value="products">Selected products</option><option value="categories">Selected categories</option><option value="combos">Selected combos</option></select></label>
  <label>Discount value<input name="discountValue" type="number" min="0" step="0.01" defaultValue={edit?.discount_value||0}/></label><label>Minimum subtotal<input name="minimumSubtotal" type="number" min="0" step="0.01" defaultValue={edit?.minimum_subtotal||0}/></label><label>Buy quantity<input name="buyQuantity" type="number" min="1" defaultValue={edit?.buy_quantity||1}/></label><label>Free quantity<input name="getQuantity" type="number" min="1" defaultValue={edit?.get_quantity||1}/></label>
  <label>Free product<select name="rewardProductId" defaultValue={edit?.reward_product_id||""}><option value="">None</option>{catalog.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Free topping<select name="rewardToppingId" defaultValue={edit?.reward_topping_id||""}><option value="">None</option>{catalog.toppings.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
  <label>Usage limit<input name="usageLimit" type="number" min="1" defaultValue={edit?.usage_limit||""}/></label><label>Start date<input name="startsOn" type="date" defaultValue={edit?.starts_on||today()} required/></label><label>End date<input name="endsOn" type="date" defaultValue={edit?.ends_on||today()} required/></label>
  {scope!=="all"&&<label className="wide">Eligible items<select name="targetIds" multiple required size={Math.min(7,Math.max(3,targets.length))} defaultValue={edit?.target_ids||[]}>{targets.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><small>Use Ctrl/Cmd to select multiple.</small></label>}
  <label className="wide">Promotion description<textarea name="description" rows={3} defaultValue={edit?.description||""}/></label><label className="customerAuthConsent wide"><input name="active" type="checkbox" defaultChecked={edit?.active??true}/><span>Active within the selected date range</span></label><button className="adminPrimary wide">{edit?"Save promotion":"Create promotion"}</button>
 </form></section><section className="adminCard"><div className="adminCardHead"><div><span className="adminEyebrow">Sales promotions</span><h3>{items.length} promotion(s)</h3></div><button className="adminSecondary" onClick={()=>void refresh()}>{loading?"Loading…":"Refresh"}</button></div><div className="adminProductList">{items.map(item=><div className="adminProductRow" key={item.id}><div className="adminProductMain"><strong>{item.name}</strong><small>{item.badge_text} · {item.starts_on} → {item.ends_on} · Used {item.usage_count}{item.usage_limit?`/${item.usage_limit}`:""}</small></div><span className={item.active?"adminState live":"adminState hidden"}>{item.active?"Active":"Paused"}</span><div className="adminRowActions"><button onClick={()=>beginEdit(item)}>Edit</button></div></div>)}</div></section></div>;
}
